# syntax=docker/dockerfile:1

FROM arm64v8/golang:1.16-alpine

ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY *.go ./

RUN go build -o /server

EXPOSE 3000

CMD [ "/server" ]