version: 2.1
jobs:
  build_and_push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: |
          curl -X POST \
            -H "Content-type: application/json" \
            -H "Authorization: Bearer $SLACK_APP_TOKEN" \
            --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"Starting build for $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1\"}" \
            https://slack.com/api/chat.postMessage
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build . -t $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
      - run:
          name: Build Docker image latest
          command: docker build . -t $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker push git ref
          command: docker push $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
  publish_config:
    docker:
      - image: ryanwholey/image-tag-updater:0.0.1
    steps:
      - run: |
          curl -X POST \
            -H "Content-type: application/json" \
            -H "Authorization: Bearer $SLACK_APP_TOKEN" \
            --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"Merging config for $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1\"}" \
            https://slack.com/api/chat.postMessage
      - run: |
          /update-git-config.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME-config $CIRCLE_SHA1
  merge_staging:
    docker:
      - image: ryanwholey/merge-release:latest
    steps:
      - run: |
          curl -X POST \
            -H "Content-type: application/json" \
            -H "Authorization: Bearer $SLACK_APP_TOKEN" \
            --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"Merging config to STAGING for $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1\"}" \
            https://slack.com/api/chat.postMessage
      - run: |
          /merge-release.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME-config staging
  release_staging:
    docker:
      - image: argoproj/argocd:v1.6.0
    steps:
      - run: |
          argocd login

          echo "Running as ArgoCD User:"
          argocd account get-user-info --grpc-web
          
          argocd app sync $CIRCLE_PROJECT_REPONAME-staging --grpc-web
          argocd app wait $CIRCLE_PROJECT_REPONAME-staging --health --grpc-web
workflows:
  version: 2
  default:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: master
      - publish_config:
          context: publish
          requires:
            - build_and_push
          filters:
            branches:
              only: master
      - merge_staging:
          context: publish
          requires:
            - publish_config
          filters:
            branches:
              only: master
      - release_staging:
          context: publish
          requires:
            - merge_staging
          filters:
            branches:
              only: master