orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  build_and_push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - slack/notify:
          channel: $SLACK_CHANNEL_ID
          color: '#42e2f4'
          message: Starting $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 build
          webhook: $SLACK_WEBHOOK
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build . -t $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
      - run:
          name: Build Docker image latest
          command: docker build . -t $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker push git ref
          command: docker push $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
  publish_config:
    docker:
      - image: ryanwholey/image-tag-updater:0.0.1
    steps:
      - slack/notify:
          channel: $SLACK_CHANNEL_ID
          color: '#42e2f4'
          message: Merging config for $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 build
          webhook: $SLACK_WEBHOOK
      - run: /update-git-config.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME-config $CIRCLE_SHA1
workflows:
  version: 2
  default:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: master
      - publish_config:
          context: publish
          requires:
            - build_and_push
          filters:
            branches:
              only: master
